api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("get/", views.api_get, name="api_get"),
    path("post/", views.api_post, name="api_post"),
]

flupi/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('chatbot/', include('chatbot.urls')),
    path('api/', include('api.urls')),
    path('notify/', include('notify.urls')),
    path('login/', include('login.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
]

api/routes.py
from flask import Blueprint, render_template
from flask import request

import json

from api import logic

from security.protected_routes import requerir_autenticacion
from security.protected_api import token_required

api_bp = Blueprint('api', __name__, url_prefix='/api', static_folder='static', template_folder='templates')

# API para el chatbot
@api_bp.route("/", methods=['GET'])
@requerir_autenticacion
def api_get():
    with open('./api/static/info.json', 'r') as file:
        json_data = json.load(file)
    return render_template('api_information.html', json=json_data)

@api_bp.route("/", methods=['POST'])
@token_required
def api_post():
    data = request.get_json()

    print(f'User: <<{data["user"]}>> Token: <<{data["token"]}>>')

    if str(data['device']).lower() == 'bot':
        return logic.bot(data)
    
    if data['ask'].isdigit():
        return logic.productos(data)
    
    return logic.computer(data)

chat/routes.py
from flask import Blueprint, render_template
from flask import request
from flask import jsonify
from flask import url_for

from databases import usuarios

import requests

chat_bp = Blueprint('chatbot', __name__, url_prefix='/chatbot', template_folder='templates', static_folder='static')

# Chatbot Front
@chat_bp.route('/', methods=['GET'])
def chatbot_get():
    return render_template('chatbot.html')


# Chatbot Back
@chat_bp.route('/', methods=['POST'])
def chatbot_post():
    data = request.get_json()
    token = usuarios.get_user_by_username('chatbot')[1]

    data = {
        "user": "Chatbot",
        "device": "computer",
        "ask": data['ask'],
        "token": token
    }

    try:
        response = requests.post('http://127.0.0.1:5000/api', json=data)

        print('<<Status>>: ', str(response.status_code))
        if "200" not in str(response.status_code):
            response = requests.post('https://127.0.0.1:5000/api', json=data)

        return jsonify(response.json())
    
    except Exception as e:
        print(f'Error: {e}')
        return jsonify({"response": str(e)})

configs/routes.py
from flask import Blueprint, render_template
from flask import request
from flask import jsonify

from databases import contextos
from databases import images
from databases import home as content

from security.protected_routes import requerir_autenticacion

configs_bp = Blueprint('configs', __name__, url_prefix='/configs', template_folder='templates', static_folder='static')

# Ruta para modificar el contexto
@configs_bp.route('/context/<filename>', methods=['GET'])
@requerir_autenticacion
def get_context(filename):
    content = contextos.get_context(filename)

    return jsonify({
        'filename': filename, 
        'content': content
    })

@configs_bp.route('/context/<filename>', methods=['POST'])
@requerir_autenticacion
def update_context(filename):
    content = request.json.get('content')
    content = contextos.update_context(filename, content)
    if content:
        salida = 'File updated successfully'
    else:
        salida = 'Error'

    return jsonify({
        'filename': filename, 
        'message': salida
    })

@configs_bp.route('/context_f/', methods=['GET'])
@requerir_autenticacion
def read_context():
    context_files = contextos.get_context_all()
    return render_template('context.html', files=context_files)


# Rutas para las imagenes
@configs_bp.route('/images/<filename>', methods=['GET'])
@requerir_autenticacion
def get_image_route(filename):
    image_data = images.get_image(filename)

    if image_data != 'Image not found':
        return jsonify({'filename': filename, 'content': image_data})
    else:
        return jsonify({'message': 'Image not found'})

@configs_bp.route('/images/<filename>', methods=['POST'])
@requerir_autenticacion
def update_image_route(filename):
    new_image = request.files['new_image']
    new_image_data = new_image.read()

    result = images.update_image(filename, new_image_data)

    if result == "Imagen actualizada correctamente en la base de datos.":
        return jsonify({'filename': filename, 'message': 'File updated successfully'})
    else:
        return jsonify({'filename': filename, 'message': result})

@configs_bp.route('/images_f/', methods=['GET'])
@requerir_autenticacion
def read_images_route():
    image_names = images.get_image_all()
    return render_template('change_images.html', files=image_names)
    

# HOME
@configs_bp.route('home_config', methods=['GET'])
@requerir_autenticacion
def home_config_get():
    html = content.get_home()
    return render_template('home_config.html', html=html)

@configs_bp.route('home_config', methods=['POST'])
@requerir_autenticacion
def home_config_post():
    data = request.json.get('content') 
    response = content.update_home(data=data)
    return jsonify(response)

home/routes.py
from flask import Blueprint, render_template

from databases import home as content

home_bp = Blueprint('home', __name__, url_prefix='/home', template_folder='templates', static_folder='static')

# Home
@home_bp.route('/', methods=['GET'])
def home():
    html = content.get_home()
    return render_template('index.html', html=html)

home/views.py
from django.shortcuts import render

from django.contrib.auth.decorators import login_required

# Views from home
@login_required
def home(request):
    return render(request, 'home.html')

widget/routes.py
from flask import Blueprint 
from flask import jsonify

from dotenv import load_dotenv
load_dotenv()

from databases import images

from chat.routes import chatbot_post

widget_bp = Blueprint('widget', __name__, url_prefix='/widget', template_folder='templates', static_folder='static')

@widget_bp.route('/', methods=['POST'])
def widget_post():
    return chatbot_post()

@widget_bp.route('photos/', methods=['GET'])
def widget_get():
    try:
        photo_chatbot = images.get_image('chatbot')
    except Exception as e:
        print("Error: ", e)
        photo_chatbot = ''
    
    try:
        photo_user = images.get_image('usuario')
    except Exception as e:
        print("Error: ", e)
        photo_user = ''
    
    return jsonify({
        "photo_user": photo_user,
        "photo_role": photo_chatbot
    })

home/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="icon" href="{{ url_for('home.static', filename='compumax.jpeg') }}" type="image/jpeg">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('home.static', filename='style.css') }}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-ligth bg-ligth">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="{{ url_for('home.static', filename='compumax_banner.jpeg') }}" height="50" class="d-inline-block align-center" alt="">
            </a>
    
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    {% if 'username' in session %}
                        <li class="nav-item">
                            <p class="nav-link user">Bienvenido, {{ session['username'] }}!</p>
                        </li>
                        <li class="nav-item">
                            <a href="{{ url_for('security.logout') }}" class="nav-link">Cerrar sesión 🔒</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a href="{{ url_for('security.login') }}" class="nav-link">Iniciar sesión 🔓</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="list-items my-class navbar-ligth bg-dark">
        <ul class="nav">
            <li class="nav-item"><a class="nav-link active" href="{{ url_for('home.home') }}">🏠 Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('chatbot.chatbot_get') }}">✉️ Chatbot</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('notify.notify_frontend') }}">🔔 Notify</a></li>
            {% if 'username' in session %}
            <li class="nav-item"><a class="nav-link" href="{{ url_for('api.api_get') }}">🌐 API</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('configs.home_config_get') }}">⚙️ Configuración Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('configs.read_context') }}">⚙️ Contextos</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('configs.read_images_route') }}">📷 Imagenes</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('security.view_users') }}">👥 Usuarios</a></li>
            {% endif %}
        </ul>
    </div>

    <div class="content">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Ejemplo de integración del Widget-->
    <link rel="stylesheet" href="{{ url_for('widget.static', filename='style_chat_pop.css') }}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{{ url_for('widget.static', filename='script_widget.js') }}"></script>
    <!-- URL a la que va apuntar el Widget -->
    <script> init("{{ url_for('widget.widget_post') }}"); </script>

    <!-- Botón de apertura del chat -->
    <div id="chat-open-btn">Abrir Chat</div>

    <!-- Cuadro de diálogo emergente -->
    <div id="chat-popup">
        <div id="chat-container" class="container_chat">
            <div id="title">Bienvenid@</div>
            <div id="chat-messages" class="chat-box">
                <!-- Aquí se mostrarán los mensajes de la conversación -->
            </div>
            <form id="chat-form" class="chat-input">
                <input type="text" id="message-input" class="form-control" placeholder="Escribe un mensaje...">
                <button type="submit" class="btn btn-outline-primary">Enviar</button>
            </form>
        </div>
    </div>

</body>
</html>

home/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Home {% endblock %}
{% block subtitle %} Home {% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>Bienvenido a CompuMax - Asistente de Ventas</h1>
        
                <div class="section">
                    <h2>¿Qué es CompuMax?</h2>
                    <p>
                        CompuMax es una empresa de tecnología con más de veinticuatro años de experiencia.
                        Ofrecemos una amplia gama de productos y servicios informáticos, desde desarrollo
                        de software a medida hasta reparación de dispositivos y venta de equipos.
                        Nuestro compromiso es brindar soluciones de alta calidad adaptadas a las necesidades
                        de nuestros clientes.
                    </p>
                </div>

                <div class="section">
                    <h2>¿Cómo hacer preguntas al bot?</h2>
                    <p>
                        Puedes hacer preguntas al asistente de ventas ingresando tu consulta en el espacio
                        designado y presionando el botón para enviarla. El asistente intentará proporcionarte
                        una respuesta relevante relacionada con informática y los servicios que ofrece CompuMax.
                        Recuerda utilizar términos informáticos y ser claro en tu consulta.
                    </p>
                    <p>
                        Ejemplo de pregunta: "¿Cuáles son las aplicaciones destacadas de CompuMax?"
                    </p>
                </div>
            </div>

            <div class="col-md-6">
                <!-- Video -->
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="{% static 'video.mp4' %}" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

home/templates/index.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}
{% block subtitle %} Home {% endblock %}

{% block content %}
 {{ html | safe }}
{% endblock %}