api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("get/", views.api_get, name="api_get"),
    path("post/", views.api_post, name="api_post"),
]

flupi/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('chatbot/', include('chatbot.urls')),
    path('api/', include('api.urls')),
    path('notify/', include('notify.urls')),
    path('login/', include('login.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

notify/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.notify_frontend, name="notify"),
    path("status/", views.notify_status, name="notify_status"),
    path("entry/<int:statuswork>", views.notify_backend, name="notify_entry"),
]

notify/models.py
from django.db import models

# Create your models here.
class StatusWork(models.Model):
    id = models.AutoField(primary_key=True)
    status = models.BooleanField()

    def __str__(self) -> str:
        return f'{self.id} Estado: {self.status}'

notify/routes.py
from flask import Blueprint, render_template
from flask import jsonify
from flask import redirect, url_for

from databases import alarm

notify_bp = Blueprint('notify', __name__, url_prefix='/notify', template_folder='templates', static_folder='static')

# Notify Front
@notify_bp.route('/notify_f', methods=['GET'])
def notify_frontend():
    return render_template('notify.html')

# Notify Status
@notify_bp.route('/', methods=['GET'])
def notify_status():
    work = alarm.get_alarm_status()

    return jsonify({
        "status": work
    })

# Notify Back
@notify_bp.route("/<int:statuswork>", methods=["GET"])
def notify_backend(statuswork):
    """
    Parámetros:
        - statuswork (int): 1 para llamar al técnico, 0 para desactivar.
    Retorna: Redirección a la página 'notify_f'.
    """
    alarm.update_alarm_status(statuswork)
    return redirect(url_for('notify.notify_frontend'))

notify/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http.response import JsonResponse

from django.contrib.auth.decorators import login_required

from .models import StatusWork

# Notify Front
@login_required
def notify_frontend(request):
    return render(request, 'notify.html')

# Notify Status
def notify_status(request):
    work = StatusWork.objects.filter(id=1).values()[0]

    return JsonResponse({
        "status": work['status']
    })

# Notify Back
@login_required
def notify_backend(request, statuswork):
    """
    Parámetros:
        - statuswork (int): 1 para llamar al técnico, 0 para desactivar.
    Retorna: Redirección a la página 'notify_f'.
    """
    status_obj = StatusWork.objects.get(id=1)

    # Convertir el parámetro a un valor booleano
    if statuswork == 0:
        status_obj.status = False
        status_obj.save()
    if statuswork == 1:
        status_obj.status = True
        status_obj.save()

    return redirect('notify')

notify/templates/notify.html
{% extends 'base.html' %}

{% block title %} Notify {% endblock %}
{% block subtitle %} Notify {% endblock %}

{% block content %}
    <link rel="stylesheet" href="{{ url_for('notify.static', filename='style.css') }}">
    <div class="container py-4">
        <div class="box" id="box">
            <p id="status" class="text-center">No ha cambiado</p>
        </div>

        <div class="d-grid gap-2">
            <button id="boton" class="btn btn-primary btn-lg">Ya Salgo</button>
        </div>

        <audio id="audio" src="{{ url_for('notify.static', filename='sonido.mp3') }}" preload="auto">Ringtone</audio>
    </div>
    
    <script>
    // URL de la API que deseas observar
    let apiUrl = "{{ url_for('notify.notify_status') }}";
    apiUrl = apiUrl.replace(/^http:\/\//i, 'https://');
    console.log(apiUrl);

    // Obtenemos el parrafo que va a servir como identificador
    let mensaje = document.getElementById("status");
    let caja = document.getElementById("box");
    let audio = document.getElementById("audio");
    const boton = document.getElementById("boton");

    // Mensajes a mostrar 
    let mensaje_clientes = "Cliente Afuera!!!";
    let mensaje_no_clientes = "No hay clientes";

    // Variable para controlar el estado del audio
    let audioActivo = false;

    // Función para activar/desactivar el audio
    function toggleAudio(activar) {
        if (activar) {
            audio.play();
            audio.loop = true;
        } else {
            audio.pause();
            audio.loop = false;
        }
    }

    // Reproducimos el sonido hasta que presione el boton
    boton.addEventListener("click", function (event) {
        event.preventDefault();
        if (audioActivo) {
            toggleAudio(false);
            audioActivo = false;
        }
        window.location.href = "/notify/0";
    });

    // Función para realizar la solicitud a la API y verificar cambios
    async function checkForChanges() {
        try {
            const response = await fetch(apiUrl);
            if (response.status === 200) {
                // Obtenemos el json de la API
                const data = await response.json();
                if (data.status != false) {
                    mensaje.innerHTML = mensaje_clientes;
                    caja.style.backgroundColor = "#94351b";
                    if (!audioActivo) {
                        toggleAudio(true);
                        audioActivo = true;
                    }
                } else {
                    mensaje.innerHTML = mensaje_no_clientes;
                    caja.style.backgroundColor = "#CCCCCC";
                    if (audioActivo) {
                        toggleAudio(false);
                        audioActivo = false;
                    }
                }
            } else {
                alert("Error al obtener datos de la API");
            }
        } catch (error) {
            alert('Error en la solicitud a la API', error);
        }
    }

    // Realizar la verificación cada cierto tiempo (por ejemplo, cada 1 segundo)
    setInterval(checkForChanges, 1000);
    </script>

{% endblock %}