api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("get/", views.api_get, name="api_get"),
    path("post/", views.api_post, name="api_post"),
]

flupi/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('chatbot/', include('chatbot.urls')),
    path('api/', include('api.urls')),
    path('notify/', include('notify.urls')),
    path('login/', include('login.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

login/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.signin, name="signin"),
    path("signup/", views.signup, name="signup"),
    path("signout/", views.signout, name="signout")
]

login/models.py
from django.db import models

# Create your models here.

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError

# Create your views here.
def signin(request):
    if request.method == "GET":
        return render(request, 'signin.html', {
            "form": AuthenticationForm
        })
    
    user = authenticate(
        request, username=request.POST['username'], password=request.POST['password']
    )

    if user is None:
        return render(request, "signin.html", {
            "error": "Usuario o contraseña incorrectos"
        })
    
    login(request, user)
    return redirect("home")

def signup(request):
    if request.method == "GET":
        return render(request, "signup.html", {
            "form": UserCreationForm
        })
    
    if request.POST["password1"] == request.POST["password2"]:
        try:
            user = User.objects.create_user(
                request.POST["username"], password=request.POST["password2"]
            )
            user.save()
            login(request, user)
            return redirect("home")
        
        except IntegrityError:
            return render(request, "signup.html", {
                "form": UserCreationForm,
                "error": "Usuario ya existe"
            })

@login_required
def signout(request):
    logout(request)
    return redirect("signin")

security/routes.py
from flask import Blueprint 
from flask import render_template
from flask import request
from flask import session
from flask import redirect
from flask import url_for

from databases import usuarios
from security.protected_routes import requerir_autenticacion

from dotenv import load_dotenv
load_dotenv()

import os

security_bp = Blueprint('security', __name__, url_prefix='/security', template_folder='templates', static_folder='static')

@security_bp.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        user = usuarios.get_user_by_username(username)
        if user and usuarios.search_user(username, password):
            session['username'] = username
            return redirect(url_for('home.home'))
        else:
            error = "Credenciales inválidas"
            return render_template('login.html', error=error)

    return render_template('login.html')

@security_bp.route('/logout/')
def logout():
    session.pop('username', None)
    return redirect(url_for('security.login'))


# Esta ruta es solo accesible si se tiene acceso al sistema
@security_bp.route('/signup', methods=['GET', 'POST'])
@requerir_autenticacion
def signup():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        if usuarios.get_user_by_username(username):
            error = "El nombre de usuario ya está en uso. Por favor, elige otro."
            return render_template('signup.html', error=error)

        usuarios.create_user(username, password)
        return redirect(url_for('security.login'))

    return render_template('signup.html')

# Gestion de usuarios
@security_bp.route('/users')
@requerir_autenticacion
def view_users():
    users = usuarios.get_all_users()
    return render_template('view_users.html', users=users)

@security_bp.route('/delete_user/<user_id>', methods=['GET', 'POST'])
@requerir_autenticacion
def delete_user(user_id):
    if request.method == 'POST':
        password = request.form['password']

        if password == os.environ.get('ADMIN_KEY'):
            usuarios.delete_user_by_id(user_id)
            return redirect(url_for('security.view_users'))
        else:
            error = "Contraseña incorrecta para eliminar usuario."
            return render_template('delete_user.html', error=error)

    return render_template('delete_user.html')

security/templates/base_login.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>

{% block content %}

{% endblock %}

</body>
</html>

security/templates/delete_user.html
<!-- delete_user.html -->

{% extends "base.html" %}
{% block content %}
    <link rel="stylesheet" href="{{ url_for('security.static', filename='delete_style.css') }}">
    <h1>Eliminar Usuario</h1>
    <form method="post" class="delete-form">
        <label for="password">Ingrese la contraseña para eliminar el usuario:</label>
        <input type="password" id="password" name="password" class="password-input">
        <button type="submit" class="delete-button">Eliminar &#128465;</button>
        {% if error %}
            <p class="error-message">&#9888; {{ error }}</p>
        {% endif %}
    </form>
{% endblock %}

security/templates/login.html
{% extends 'base_login.html' %}

{% block title %}🔒 Login {% endblock %}

{% block content %}
   <link rel="stylesheet" href="{{ url_for('security.static', filename='login_style.css') }}">
    <form action="{{ url_for('security.login') }}" method="post">
        <h1>🔒 Iniciar sesión</h1>
        {% if error %}
            <p style="color: red;">{{ error }}</p>
        {% endif %}
        <label for="username">Usuario:</label>
        <input type="text" id="username" name="username" required><br>
        <label for="password">Contraseña:</label>
        <input type="password" id="password" name="password" required><br>
        <input type="submit" value="Iniciar sesión">
    </form>
{% endblock %}

security/templates/signup.html
{% extends 'base_login.html' %}

{% block title %}📝 SignUp {% endblock %}

{% block content %}
    <link rel="stylesheet" href="{{ url_for('security.static', filename='signup_style.css') }}">
    <div class="signup-form">
        <h1>📝 Registro de usuario</h1>
        {% if error %}
            <p style="color: red;">{{ error }}</p>
        {% endif %}
        <form action="{{ url_for('security.signup') }}" method="post">
            <label for="username">Nombre de usuario:</label>
            <input type="text" id="username" name="username" required><br>
            <label for="password">Contraseña:</label>
            <input type="password" id="password" name="password" required><br>
            <input type="submit" value="Registrarse">
        </form>
        <p>¿Ya tienes una cuenta? <a href="{{ url_for('security.login') }}">Inicia sesión</a></p>
    </div>

{% endblock %}

security/templates/view_users.html
<!-- view_users.html -->

{% extends "base.html" %}
{% block content %}
    <h1>Lista de Usuarios</h1>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>Nombre de Usuario</th>
                    <th>Token</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{ user[2] }}</td>
                        <td>{{ user[1] }}</td>

                        <td>
                            <a href="{{ url_for('security.delete_user', user_id=user[2]) }}" class="btn btn-danger">Eliminar &#128465;</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <a href="{{ url_for('security.signup') }}" class="btn btn-success">➕ Añadir nuevo Usuario</a>
{% endblock %}